import os

# Simple translation system with predefined phrases
# This doesn't require an external API

# Common phrases dictionary for agricultural terms
TRANSLATIONS = {
    # English phrases
    "en": {
        "welcome": "Welcome to AgriSaarthi",
        "crop_recommendation": "Crop Recommendation",
        "fertilizer_recommendation": "Fertilizer Recommendation",
        "disease_detection": "Disease Detection",
        "farm_diary": "Farm Diary",
        "task_planner": "Task Planner",
        "knowledge_hub": "Knowledge Hub",
        "login": "Login",
        "register": "Register",
        "logout": "Logout",
        "profile": "Profile",
        "home": "Home",
        "submit": "Submit",
        "cancel": "Cancel",
        "save": "Save",
        "delete": "Delete",
        "edit": "Edit",
        "your_smart_farming_assistant": "Your AI-Driven Smart Farming Assistant",
        "homepage_description": "Revolutionizing Indian agriculture with intelligent crop recommendations, fertilizer suggestions, plant disease detection, and smart farm management tools — all accessible in multiple Indian languages.",
        "explore_features": "Explore Features",
        "get_started": "Get Started",
        "get_crop_recommendations": "Get Crop Recommendations",
        "username": "Username",
        "password": "Password",
        "email": "Email",
        "forgot_password": "Forgot Password",
        "already_have_account": "Already have an account?",
        "dont_have_account": "Don't have an account?",
        "sign_up": "Sign Up",
        "sign_in": "Sign In",
        "nitrogen": "Nitrogen",
        "phosphorus": "Phosphorus",
        "potassium": "Potassium",
        "temperature": "Temperature",
        "humidity": "Humidity",
        "ph": "pH",
        "rainfall": "Rainfall",
        "crop_type": "Crop Type",
        "soil_type": "Soil Type",
        "plant_image": "Plant Image",
        "predict_crop": "Predict Crop",
        "predict_fertilizer": "Predict Fertilizer",
        "detect_disease": "Detect Disease",
        "result": "Result",
        "recommended_crop": "Recommended Crop",
        "recommended_fertilizer": "Recommended Fertilizer",
        "detected_disease": "Detected Disease",
        "treatment": "Treatment",
        "prevention": "Prevention",
        "upload_image": "Upload Image",
        "entry_type": "Entry Type",
        "date": "Date",
        "amount": "Amount",
        "details": "Details",
        "crop": "Crop",
        "add_entry": "Add Entry",
        "export_diary": "Export Diary",
        "task_name": "Task Name",
        "task_date": "Task Date",
        "task_type": "Task Type",
        "task_details": "Task Details",
        "add_task": "Add Task",
        "completed": "Completed",
        "pending": "Pending",
        "mark_complete": "Mark Complete",
        "search": "Search",
        "filter": "Filter",
        "sowing": "Sowing",
        "irrigation": "Irrigation",
        "fertilizing": "Fertilizing",
        "harvesting": "Harvesting",
        "income": "Income",
        "expense": "Expense",
        "today": "Today",
        "tomorrow": "Tomorrow",
        "next_week": "Next Week",
        "next_month": "Next Month",
    },
    # Hindi phrases
    "hi": {
        "welcome": "अग्रिसारथी में आपका स्वागत है",
        "crop_recommendation": "फसल अनुशंसा",
        "fertilizer_recommendation": "उर्वरक अनुशंसा",
        "disease_detection": "रोग पहचान",
        "farm_diary": "खेत डायरी",
        "task_planner": "कार्य योजना",
        "knowledge_hub": "ज्ञान केंद्र",
        "login": "लॉगिन",
        "register": "पंजीकरण",
        "logout": "लॉगआउट",
        "profile": "प्रोफाइल",
        "home": "होम",
        "submit": "जमा करें",
        "cancel": "रद्द करें",
        "save": "सहेजें",
        "delete": "हटाएं",
        "edit": "संपादित करें",
        "your_smart_farming_assistant": "आपका एआई-संचालित स्मार्ट कृषि सहायक",
        "homepage_description": "बुद्धिमान फसल अनुशंसाओं, उर्वरक सुझावों, पौधों की बीमारी का पता लगाने और स्मार्ट खेत प्रबंधन उपकरणों के साथ भारतीय कृषि में क्रांति — सभी कई भारतीय भाषाओं में उपलब्ध हैं।",
        "explore_features": "विशेषताएं देखें",
        "get_started": "आरंभ करें",
        "get_crop_recommendations": "फसल अनुशंसाएँ प्राप्त करें",
        "username": "उपयोगकर्ता नाम",
        "password": "पासवर्ड",
        "email": "ईमेल",
        "forgot_password": "पासवर्ड भूल गए",
        "already_have_account": "क्या आपके पास पहले से एक खाता है?",
        "dont_have_account": "क्या आपके पास खाता नहीं है?",
        "sign_up": "साइन अप करें",
        "sign_in": "साइन इन करें",
        "nitrogen": "नाइट्रोजन",
        "phosphorus": "फास्फोरस",
        "potassium": "पोटैशियम",
        "temperature": "तापमान",
        "humidity": "आर्द्रता",
        "ph": "पीएच",
        "rainfall": "वर्षा",
        "crop_type": "फसल प्रकार",
        "soil_type": "मिट्टी प्रकार",
        "plant_image": "पौधे की छवि",
        "predict_crop": "फसल की भविष्यवाणी करें",
        "predict_fertilizer": "उर्वरक की भविष्यवाणी करें",
        "detect_disease": "रोग का पता लगाएं",
        "result": "परिणाम",
        "recommended_crop": "अनुशंसित फसल",
        "recommended_fertilizer": "अनुशंसित उर्वरक",
        "detected_disease": "पता लगाया गया रोग",
        "treatment": "उपचार",
        "prevention": "रोकथाम",
        "upload_image": "छवि अपलोड करें",
        "entry_type": "प्रविष्टि प्रकार",
        "date": "तारीख",
        "amount": "राशि",
        "details": "विवरण",
        "crop": "फसल",
        "add_entry": "प्रविष्टि जोड़ें",
        "export_diary": "डायरी निर्यात करें",
        "task_name": "कार्य नाम",
        "task_date": "कार्य तिथि",
        "task_type": "कार्य प्रकार",
        "task_details": "कार्य विवरण",
        "add_task": "कार्य जोड़ें",
        "completed": "पूरा हुआ",
        "pending": "लंबित",
        "mark_complete": "पूर्ण चिह्नित करें",
        "search": "खोज",
        "filter": "फ़िल्टर",
        "sowing": "बुवाई",
        "irrigation": "सिंचाई",
        "fertilizing": "उर्वरकीकरण",
        "harvesting": "कटाई",
        "income": "आय",
        "expense": "व्यय",
        "today": "आज",
        "tomorrow": "कल",
        "next_week": "अगले सप्ताह",
        "next_month": "अगले महीने",
    },
    # Tamil phrases
    "ta": {
        "welcome": "அக்ரிசாரதிக்கு வரவேற்கிறோம்",
        "crop_recommendation": "பயிர் பரிந்துரை",
        "fertilizer_recommendation": "உர பரிந்துரை",
        "disease_detection": "நோய் கண்டறிதல்",
        "farm_diary": "பண்ணை நாட்குறிப்பு",
        "task_planner": "பணி திட்டமிடல்",
        "knowledge_hub": "அறிவு மையம்",
        "login": "உள்நுழைய",
        "register": "பதிவு செய்யவும்",
        "logout": "வெளியேறு",
        "profile": "சுயவிவரம்",
        "home": "முகப்பு",
        "submit": "சமர்ப்பிக்கவும்",
        "cancel": "ரத்து செய்",
        "save": "சேமி",
        "delete": "நீக்கு",
        "edit": "திருத்து",
    },
    # Telugu phrases
    "te": {
        "welcome": "అగ్రిసారథికి స్వాగతం",
        "crop_recommendation": "పంట సిఫార్సు",
        "fertilizer_recommendation": "ఎరువుల సిఫార్సు",
        "disease_detection": "వ్యాధి గుర్తింపు",
        "farm_diary": "వ్యవసాయ డైరీ",
        "task_planner": "పని ప్రణాళిక",
        "knowledge_hub": "జ్ఞాన కేంద్రం",
        "login": "లాగిన్",
        "register": "నమోదు",
        "logout": "లాగౌట్",
        "profile": "ప్రొఫైల్",
        "home": "హోమ్",
        "submit": "సమర్పించండి",
        "cancel": "రద్దు చేయండి",
        "save": "సేవ్ చేయండి",
        "delete": "తొలగించండి",
        "edit": "సవరించండి",
    },
    # Bengali phrases
    "bn": {
        "welcome": "অগ্রিসারথিতে আপনাকে স্বাগতম",
        "crop_recommendation": "ফসল সুপারিশ",
        "fertilizer_recommendation": "সার সুপারিশ",
        "disease_detection": "রোগ সনাক্তকরণ",
        "farm_diary": "খামার ডায়েরি",
        "task_planner": "কাজ পরিকল্পনাকারী",
        "knowledge_hub": "জ্ঞান কেন্দ্র",
        "login": "লগইন",
        "register": "নিবন্ধন",
        "logout": "লগআউট",
        "profile": "প্রোফাইল",
        "home": "হোম",
        "submit": "জমা দিন",
        "cancel": "বাতিল করুন",
        "save": "সংরক্ষণ করুন",
        "delete": "মুছুন",
        "edit": "সম্পাদনা করুন",
    },
}

def translate_text(text, target_language='en'):
    """
    Translate text using predefined translations.
    
    Args:
        text (str): Text to translate
        target_language (str): Target language code (e.g., 'hi' for Hindi, 'ta' for Tamil)
        
    Returns:
        str: Translated text
    """
    if not text:
        return ""
    
    # Default to English if target language not supported
    if target_language not in TRANSLATIONS:
        target_language = 'en'
    
    # Look up the text in our translations dictionary
    for key, translated_text in TRANSLATIONS[target_language].items():
        if text.lower() == key.lower():
            return translated_text
        
    # If we don't have a translation, return the original text
    return text

# Dictionary of supported languages with their codes
SUPPORTED_LANGUAGES = {
    "English": "en",
    "Hindi": "hi",
    "Tamil": "ta",
    "Telugu": "te",
    "Bengali": "bn",
    "Marathi": "mr",
    "Gujarati": "gu",
    "Kannada": "kn",
    "Malayalam": "ml",
    "Punjabi": "pa",
    "Urdu": "ur"
}
