import os

# Simple translation system with predefined phrases
# This doesn't require an external API

# List of supported languages
SUPPORTED_LANGUAGES = {
    'en': 'English',
    'hi': 'हिंदी (Hindi)',
    'ta': 'தமிழ் (Tamil)',
    'te': 'తెలుగు (Telugu)',
    'bn': 'বাংলা (Bengali)'
}

# Common phrases dictionary for agricultural terms
TRANSLATIONS = {
    # English phrases
    "en": {
        "welcome": "Welcome to AgriSaarthi",
        "crop_recommendation": "Crop Recommendation",
        "fertilizer_recommendation": "Fertilizer Recommendation",
        "disease_detection": "Disease Detection",
        "farm_diary": "Farm Diary",
        "task_planner": "Task Planner",
        "knowledge_hub": "Knowledge Hub",
        "login": "Login",
        "register": "Register",
        "logout": "Logout",
        "profile": "Profile",
        "home": "Home",
        "submit": "Submit",
        "cancel": "Cancel",
        "save": "Save",
        "delete": "Delete",
        "edit": "Edit",
        "your_smart_farming_assistant": "Your AI-Driven Smart Farming Assistant",
        "homepage_description": "Revolutionizing Indian agriculture with intelligent crop recommendations, fertilizer suggestions, plant disease detection, and smart farm management tools — all accessible in multiple Indian languages.",
        "explore_features": "Explore Features",
        "get_started": "Get Started",
        "get_crop_recommendations": "Get Crop Recommendations",
        
        # Farm Diary translations
        "farmbook_title": "FarmBook - Digital Farm Diary",
        "export_to_csv": "Export to CSV",
        "add_new_entry": "Add New Entry",
        "entry_type": "Entry Type",
        "select_entry_type": "Select entry type",
        "sowing": "Sowing",
        "fertilizer_application": "Fertilizer Application",
        "irrigation": "Irrigation",
        "harvest": "Harvest",
        "expense": "Expense",
        "income": "Income",
        "date": "Date",
        "crop": "Crop",
        "crop_label": "Crop",
        "crop_placeholder": "e.g., Wheat, Rice, etc.",
        "details": "Details",
        "details_placeholder": "Add detailed information",
        "amount_rupees": "Amount (₹)",
        "amount_placeholder": "Enter amount in Rupees",
        "add_entry": "Add Entry",
        "your_farm_diary": "Your Farm Diary",
        "total_income": "Total Income",
        "total_expense": "Total Expense",
        "search_entries": "Search entries...",
        "all_types": "All Types",
        "fertilizer": "Fertilizer",
        "confirm_delete_entry": "Are you sure you want to delete this entry?",
        "no_entries_yet": "No entries yet",
        "start_tracking_message": "Start tracking your farming activities by adding entries.",
        
        # Knowledge Hub translations
        "knowledge_hub_title": "Farming Knowledge Hub",
        "knowledge_hub_description": "Access comprehensive guides and resources for both beginners and experienced farmers",
        "search_knowledge_placeholder": "Search articles, guides, and resources...",
        "search": "Search",
        "knowledge_categories": "Knowledge Categories",
        "soil_management": "Soil Management",
        "soil_management_description": "Learn about soil types, testing, improvement techniques, and conservation practices.",
        "crop_selection": "Crop Selection",
        "crop_selection_description": "Discover seasonal crop guides, rotation practices, and region-specific recommendations.",
        "farming_equipment": "Farming Equipment",
        "farming_equipment_description": "Understand basic and advanced equipment, maintenance tips, and selection guides.",
        "water_management": "Water Management",
        "water_management_description": "Learn about irrigation systems, water conservation, rainwater harvesting, and drainage solutions.",
        "pest_management": "Pest Management",
        "pest_management_description": "Identify common pests and discover natural and chemical control methods for crop protection.",
        "organic_farming": "Organic Farming",
        "organic_farming_description": "Learn techniques for chemical-free farming, natural pest control, and organic certification.",
        "explore": "Explore",
        
        # Knowledge Hub article translations
        "understanding_soil_types_title": "Understanding Soil Types and Their Properties",
        "beginner_level": "Beginner",
        "ten_min_read": "10 min read",
        "soil_types_intro": "Soil is the foundation of successful farming. Different soil types have varying characteristics that affect water retention, nutrient availability, and crop growth.",
        "major_soil_types_heading": "Major Soil Types in India",
        "soil_properties_heading": "Understanding Soil Properties",
        "key_properties_intro": "Key properties to understand include",
        "black_soil": "Black Soil (Regur)",
        "black_soil_desc": "Rich in clay, good for cotton and sugarcane",
        "alluvial_soil": "Alluvial Soil",
        "alluvial_soil_desc": "Found in river basins, excellent for most crops",
        "red_soil": "Red Soil",
        "red_soil_desc": "Contains iron oxide, suitable for millets and pulses",
        "laterite_soil": "Laterite Soil",
        "laterite_soil_desc": "Found in high rainfall areas, requires nutrient management",
        "desert_soil": "Desert Soil",
        "desert_soil_desc": "Sandy texture, low fertility, requires irrigation",
        "soil_texture": "Texture",
        "soil_texture_desc": "The proportion of sand, silt, and clay", 
        "soil_structure": "Structure",
        "soil_structure_desc": "How soil particles arrange themselves",
        "soil_ph": "pH Level",
        "soil_ph_desc": "Acidity or alkalinity (optimal range: 6.0-7.5 for most crops)",
        "organic_matter": "Organic Matter",
        "organic_matter_desc": "Decayed plant and animal material that improves fertility",
        "water_holding": "Water Holding Capacity",
        "water_holding_desc": "Ability to retain moisture for plant use",
        "read_full_article": "Read Full Article",
        
        # Crop Recommendation translations
        "crop_recommendation_system": "Crop Recommendation System",
        "crop_recommendation_description": "Enter your soil parameters and climate conditions to get AI-powered crop recommendations suitable for your farm.",
        
        # Fertilizer Recommendation translations
        "fertilizer_recommendation_system": "Fertilizer Recommendation System",
        "fertilizer_recommendation_description": "Enter your soil nutrient levels and crop type to receive recommendations for the most appropriate fertilizers.",
        "fertilizer_recommendation_info": "Different crops have varying nutrient requirements. For optimal results, enter accurate soil test data and select the specific crop you plan to grow.",
        "crop_type_label": "Crop Type",
        "select_crop": "Select crop",
        "get_fertilizer_recommendation": "Get Fertilizer Recommendation",
        
        # Crop names for selection dropdown
        "rice": "Rice",
        "wheat": "Wheat",
        "maize": "Maize",
        "chickpea": "Chickpea",
        "lentil": "Lentil",
        "cotton": "Cotton",
        "sugarcane": "Sugarcane",
        "tea": "Tea",
        "coffee": "Coffee",
        "potato": "Potato",
        "tomato": "Tomato",
        "onion": "Onion",
        "mustard": "Mustard",
        "soybean": "Soybean",
        "groundnut": "Groundnut",
        
        # Disease Detection translations
        "disease_detection_title": "Plant Disease Detection",
        "disease_detection_description": "Upload an image of a plant leaf to identify diseases, understand their causes, and get treatment recommendations.",
        "disease_detection_info": "For best results, upload a clear image in good lighting, focusing on the affected area of the plant.",
        "drag_drop_upload": "Drag & Drop or Click to Upload",
        "supported_formats": "Supported formats: JPG, JPEG, PNG",
        "remove": "Remove",
        "detect_disease": "Detect Disease",
        "disease_detection_results": "Disease Detection Results",
        "disease_name": "Disease Name",
        "disease_cause": "Disease Cause",
        "treatment_recommendations": "Treatment Recommendations",
        
        # Task Planner translations
        "task_planner_title": "KrishiCalendar - Crop Task Planner",
        "plan_new_task": "Plan New Task",
        "task_name": "Task Name",
        "task_name_placeholder": "e.g., First Fertilizer Application",
        "task_date": "Task Date",
        "task_type": "Task Type",
        "select_task_type": "Select task type",
        "irrigation": "Irrigation",
        "fertilizing": "Fertilizing",
        "harvesting": "Harvesting",
        "sowing": "Sowing",
        "pesticide": "Pesticide Application",
        "other": "Other",
        "nitrogen_content_label": "Nitrogen (N) content in soil (mg/kg)",
        "phosphorus_content_label": "Phosphorus (P) content in soil (mg/kg)",
        "potassium_content_label": "Potassium (K) content in soil (mg/kg)",
        "temperature_content_label": "Temperature (°C)",
        "humidity_content_label": "Humidity (%)",
        "ph_content_label": "pH value",
        "rainfall_content_label": "Rainfall (mm)",
        "nitrogen_placeholder": "e.g., 40",
        "phosphorus_placeholder": "e.g., 35",
        "potassium_placeholder": "e.g., 45",
        "temperature_placeholder": "e.g., 28",
        "humidity_placeholder": "e.g., 65",
        "ph_placeholder": "e.g., 6.5",
        "rainfall_placeholder": "e.g., 120",
        "predict_best_crop": "Get Crop Recommendation",
        "recommended_crop_label": "Recommended Crop",
        "crop_recommendation_result_text": "Based on your soil parameters and climate conditions, we recommend growing",
        "for_optimal_yield": "for optimal yield",
        "why_this_crop": "Why this crop?",
        "suitable_soil_nutrients": "Suitable for your soil's nutrient profile",
        "compatible_climate": "Compatible with your local climate conditions",
        "appropriate_ph_rainfall": "Appropriate for your soil pH",
        "and": "and",
        "temperature": "Temperature",
        "humidity": "Humidity",
        "ph": "pH",
        "rainfall": "Rainfall",
        "get_fertilizer_recommendations": "Get Fertilizer Recommendations",
        "how_it_works": "How It Works",
        "enter_nutrients": "Enter your soil's nutrient levels (N, P, K)",
        "add_environmental_parameters": "Add environmental parameters (temperature, humidity, pH, rainfall)",
        "ai_analyzes_data": "Our AI model analyzes your data",
        "get_recommendation": "Get a recommendation for the most suitable crop",
        "model_training_info": "The model is trained on extensive agricultural data from across different regions of India.",
        "where_to_get_soil_parameters": "Where to get soil parameters?",
        "local_agricultural_centers": "Local agricultural extension centers",
        "mobile_soil_testing": "Mobile soil testing labs",
        "krishi_vigyan_kendras": "Krishi Vigyan Kendras (KVKs)",
        "home_testing_kits": "Home testing kits (less accurate but helpful)",
        "username": "Username",
        "password": "Password",
        "email": "Email",
        "forgot_password": "Forgot Password",
        "already_have_account": "Already have an account?",
        "dont_have_account": "Don't have an account?",
        "sign_up": "Sign Up",
        "sign_in": "Sign In",
        "nitrogen": "Nitrogen",
        "phosphorus": "Phosphorus",
        "potassium": "Potassium",
        "temperature": "Temperature",
        "humidity": "Humidity",
        "ph": "pH",
        "rainfall": "Rainfall",
        "crop_type": "Crop Type",
        "soil_type": "Soil Type",
        "plant_image": "Plant Image",
        "predict_crop": "Predict Crop",
        "predict_fertilizer": "Predict Fertilizer",
        "detect_disease": "Detect Disease",
        "result": "Result",
        "recommended_crop": "Recommended Crop",
        "recommended_fertilizer": "Recommended Fertilizer",
        "detected_disease": "Detected Disease",
        "treatment": "Treatment",
        "prevention": "Prevention",
        "upload_image": "Upload Image",
        "entry_type": "Entry Type",
        "date": "Date",
        "amount": "Amount",
        "details": "Details",
        "crop": "Crop",
        "add_entry": "Add Entry",
        "export_diary": "Export Diary",
        "task_name": "Task Name",
        "task_date": "Task Date",
        "task_type": "Task Type",
        "task_details": "Task Details",
        "add_task": "Add Task",
        "completed": "Completed",
        "pending": "Pending",
        "mark_complete": "Mark Complete",
        "search": "Search",
        "filter": "Filter",
        "sowing": "Sowing",
        "irrigation": "Irrigation",
        "fertilizing": "Fertilizing",
        "harvesting": "Harvesting",
        "income": "Income",
        "expense": "Expense",
        "today": "Today",
        "tomorrow": "Tomorrow",
        "next_week": "Next Week",
        "next_month": "Next Month",
    },
    # Hindi phrases
    "hi": {
        "welcome": "अग्रिसारथी में आपका स्वागत है",
        "crop_recommendation": "फसल अनुशंसा",
        "fertilizer_recommendation": "उर्वरक अनुशंसा",
        "disease_detection": "रोग पहचान",
        "farm_diary": "खेत डायरी",
        "task_planner": "कार्य योजना",
        "knowledge_hub": "ज्ञान केंद्र",
        "login": "लॉगिन",
        "register": "पंजीकरण",
        "logout": "लॉगआउट",
        "profile": "प्रोफाइल",
        "home": "होम",
        "submit": "जमा करें",
        "cancel": "रद्द करें",
        "save": "सहेजें",
        "delete": "हटाएं",
        "edit": "संपादित करें",
        "your_smart_farming_assistant": "आपका एआई-संचालित स्मार्ट कृषि सहायक",
        "homepage_description": "बुद्धिमान फसल अनुशंसाओं, उर्वरक सुझावों, पौधों की बीमारी का पता लगाने और स्मार्ट खेत प्रबंधन उपकरणों के साथ भारतीय कृषि में क्रांति — सभी कई भारतीय भाषाओं में उपलब्ध हैं।",
        "explore_features": "विशेषताएं देखें",
        "get_started": "आरंभ करें",
        "get_crop_recommendations": "फसल अनुशंसाएँ प्राप्त करें",
        "username": "उपयोगकर्ता नाम",
        "password": "पासवर्ड",
        "email": "ईमेल",
        "forgot_password": "पासवर्ड भूल गए",
        "already_have_account": "क्या आपके पास पहले से एक खाता है?",
        "dont_have_account": "क्या आपके पास खाता नहीं है?",
        "sign_up": "साइन अप करें",
        "sign_in": "साइन इन करें",
        "nitrogen": "नाइट्रोजन",
        "phosphorus": "फास्फोरस",
        "potassium": "पोटैशियम",
        "temperature": "तापमान",
        "humidity": "आर्द्रता",
        "ph": "पीएच",
        "rainfall": "वर्षा",
        "crop_type": "फसल प्रकार",
        "soil_type": "मिट्टी प्रकार",
        "plant_image": "पौधे की छवि",
        "predict_crop": "फसल की भविष्यवाणी करें",
        "predict_fertilizer": "उर्वरक की भविष्यवाणी करें",
        "detect_disease": "रोग का पता लगाएं",
        "result": "परिणाम",
        "recommended_crop": "अनुशंसित फसल",
        "recommended_fertilizer": "अनुशंसित उर्वरक",
        "detected_disease": "पता लगाया गया रोग",
        "treatment": "उपचार",
        "prevention": "रोकथाम",
        "upload_image": "छवि अपलोड करें",
        "entry_type": "प्रविष्टि प्रकार",
        "date": "तारीख",
        "amount": "राशि",
        "details": "विवरण",
        "crop": "फसल",
        "add_entry": "प्रविष्टि जोड़ें",
        "export_diary": "डायरी निर्यात करें",
        "task_name": "कार्य नाम",
        "task_date": "कार्य तिथि",
        "task_type": "कार्य प्रकार",
        "task_details": "कार्य विवरण",
        "add_task": "कार्य जोड़ें",
        "completed": "पूरा हुआ",
        "pending": "लंबित",
        "mark_complete": "पूर्ण चिह्नित करें",
        "search": "खोज",
        "filter": "फ़िल्टर",
        "sowing": "बुवाई",
        "irrigation": "सिंचाई",
        "fertilizing": "उर्वरकीकरण",
        "harvesting": "कटाई",
        "income": "आय",
        "expense": "व्यय",
        "today": "आज",
        "tomorrow": "कल",
        "next_week": "अगले सप्ताह",
        "next_month": "अगले महीने",
    },
    # Tamil phrases
    "ta": {
        "welcome": "அக்ரிசாரதிக்கு வரவேற்கிறோம்",
        "crop_recommendation": "பயிர் பரிந்துரை",
        "fertilizer_recommendation": "உர பரிந்துரை",
        "disease_detection": "நோய் கண்டறிதல்",
        "farm_diary": "பண்ணை நாட்குறிப்பு",
        "task_planner": "பணி திட்டமிடல்",
        "knowledge_hub": "அறிவு மையம்",
        "login": "உள்நுழைய",
        "register": "பதிவு செய்யவும்",
        "logout": "வெளியேறு",
        "profile": "சுயவிவரம்",
        "home": "முகப்பு",
        "submit": "சமர்ப்பிக்கவும்",
        "cancel": "ரத்து செய்",
        "save": "சேமி",
        "delete": "நீக்கு",
        "edit": "திருத்து",
    },
    # Telugu phrases
    "te": {
        "welcome": "అగ్రిసారథికి స్వాగతం",
        "crop_recommendation": "పంట సిఫార్సు",
        "fertilizer_recommendation": "ఎరువుల సిఫార్సు",
        "disease_detection": "వ్యాధి గుర్తింపు",
        "farm_diary": "వ్యవసాయ డైరీ",
        "task_planner": "పని ప్రణాళిక",
        "knowledge_hub": "జ్ఞాన కేంద్రం",
        "login": "లాగిన్",
        "register": "నమోదు",
        "logout": "లాగౌట్",
        "profile": "ప్రొఫైల్",
        "home": "హోమ్",
        "submit": "సమర్పించండి",
        "cancel": "రద్దు చేయండి",
        "save": "సేవ్ చేయండి",
        "delete": "తొలగించండి",
        "edit": "సవరించండి",
    },
    # Bengali phrases
    "bn": {
        "welcome": "অগ্রিসারথিতে আপনাকে স্বাগতম",
        "crop_recommendation": "ফসল সুপারিশ",
        "fertilizer_recommendation": "সার সুপারিশ",
        "disease_detection": "রোগ সনাক্তকরণ",
        "farm_diary": "খামার ডায়েরি",
        "task_planner": "কাজ পরিকল্পনাকারী",
        "knowledge_hub": "জ্ঞান কেন্দ্র",
        "login": "লগইন",
        "register": "নিবন্ধন",
        "logout": "লগআউট",
        "profile": "প্রোফাইল",
        "home": "হোম",
        "submit": "জমা দিন",
        "cancel": "বাতিল করুন",
        "save": "সংরক্ষণ করুন",
        "delete": "মুছুন",
        "edit": "সম্পাদনা করুন",
    },
}

def translate_text(text, target_language='en'):
    """
    Translate text using predefined translations.
    
    Args:
        text (str): Text to translate
        target_language (str): Target language code (e.g., 'hi' for Hindi, 'ta' for Tamil)
        
    Returns:
        str: Translated text
    """
    if not text:
        return ""
    
    # Default to English if target language not supported
    if target_language not in TRANSLATIONS:
        target_language = 'en'
    
    # Look up the text in our translations dictionary
    for key, translated_text in TRANSLATIONS[target_language].items():
        if text.lower() == key.lower():
            return translated_text
        
    # If we don't have a translation, return the original text
    return text

# Dictionary of supported languages with their codes
SUPPORTED_LANGUAGES = {
    "English": "en",
    "Hindi": "hi",
    "Tamil": "ta",
    "Telugu": "te",
    "Bengali": "bn",
    "Marathi": "mr",
    "Gujarati": "gu",
    "Kannada": "kn",
    "Malayalam": "ml",
    "Punjabi": "pa",
    "Urdu": "ur"
}
