import os

# Simple translation system with predefined phrases
# This doesn't require an external API

# Common phrases dictionary for agricultural terms
TRANSLATIONS = {
    # English phrases
    "en": {
        "welcome": "Welcome to AgriSaarthi",
        "crop_recommendation": "Crop Recommendation",
        "fertilizer_recommendation": "Fertilizer Recommendation",
        "disease_detection": "Disease Detection",
        "farm_diary": "Farm Diary",
        "task_planner": "Task Planner",
        "knowledge_hub": "Knowledge Hub",
        "login": "Login",
        "register": "Register",
        "logout": "Logout",
        "profile": "Profile",
        "home": "Home",
        "submit": "Submit",
        "cancel": "Cancel",
        "save": "Save",
        "delete": "Delete",
        "edit": "Edit",
        "your_smart_farming_assistant": "Your AI-Driven Smart Farming Assistant",
        "homepage_description": "Revolutionizing Indian agriculture with intelligent crop recommendations, fertilizer suggestions, plant disease detection, and smart farm management tools — all accessible in multiple Indian languages.",
        "explore_features": "Explore Features",
        "get_started": "Get Started",
        "get_crop_recommendations": "Get Crop Recommendations",
        "username": "Username",
        "password": "Password",
        "email": "Email",
        "forgot_password": "Forgot Password",
        "already_have_account": "Already have an account?",
        "dont_have_account": "Don't have an account?",
        "sign_up": "Sign Up",
        "sign_in": "Sign In",
        "nitrogen": "Nitrogen",
        "phosphorus": "Phosphorus",
        "potassium": "Potassium",
        "temperature": "Temperature",
        "humidity": "Humidity",
        "ph": "pH",
        "rainfall": "Rainfall",
        "crop_type": "Crop Type",
        "soil_type": "Soil Type",
        "plant_image": "Plant Image",
        "predict_crop": "Predict Crop",
        "predict_fertilizer": "Predict Fertilizer",
        "detect_disease": "Detect Disease",
        "result": "Result",
        "recommended_crop": "Recommended Crop",
        "recommended_fertilizer": "Recommended Fertilizer",
        "detected_disease": "Detected Disease",
        "treatment": "Treatment",
        "prevention": "Prevention",
        "upload_image": "Upload Image",
        "entry_type": "Entry Type",
        "date": "Date",
        "amount": "Amount",
        "details": "Details",
        "crop": "Crop",
        "add_entry": "Add Entry",
        "export_diary": "Export Diary",
        "task_name": "Task Name",
        "task_date": "Task Date",
        "task_type": "Task Type",
        "task_details": "Task Details",
        "add_task": "Add Task",
        "completed": "Completed",
        "pending": "Pending",
        "mark_complete": "Mark Complete",
        "search": "Search",
        "filter": "Filter",
        "sowing": "Sowing",
        "irrigation": "Irrigation",
        "fertilizing": "Fertilizing",
        "harvesting": "Harvesting",
        "income": "Income",
        "expense": "Expense",
        "today": "Today",
        "tomorrow": "Tomorrow",
        "next_week": "Next Week",
        "next_month": "Next Month",
        "voice_crop_planner": "Voice Crop Planner",
        "voice_planner_description": "Use your voice to get personalized crop recommendations and planning advice in your preferred language.",
        "voice_assistant": "Voice Assistant",
        "help": "Help",
        "stop": "Stop",
        "voice_assistant_instructions": "Speak naturally to ask for crop recommendations based on your soil type, climate, or season.",
        "voice_shortcut_info": "Press",
        "to_activate_mic": "to activate microphone",
        "suggested_queries": "Suggested Queries",
        "soil_based_queries": "Soil-Based Queries",
        "what_to_plant_in_sandy_soil": "What should I plant in sandy soil?",
        "crops_for_black_soil": "Which crops grow well in black soil?",
        "best_crops_for_clayey_soil": "Best crops for clayey soil?",
        "seasonal_queries": "Seasonal Queries",
        "what_to_plant_in_rainy_season": "What should I plant in rainy season?",
        "winter_crop_recommendations": "Recommend crops for winter",
        "best_crops_for_summer": "Best crops for summer season?",
        "how_it_works": "How It Works",
        "speak": "Speak",
        "speak_step_description": "Ask questions about which crops to plant based on your soil, climate or season",
        "analyze": "Analyze",
        "analyze_step_description": "The system analyzes your query to generate appropriate recommendations",
        "recommend": "Recommend",
        "recommend_step_description": "Get personalized crop recommendations with planting advice",
    },
    # Hindi phrases
    "hi": {
        "welcome": "अग्रिसारथी में आपका स्वागत है",
        "crop_recommendation": "फसल अनुशंसा",
        "fertilizer_recommendation": "उर्वरक अनुशंसा",
        "disease_detection": "रोग पहचान",
        "farm_diary": "खेत डायरी",
        "task_planner": "कार्य योजना",
        "knowledge_hub": "ज्ञान केंद्र",
        "login": "लॉगिन",
        "register": "पंजीकरण",
        "logout": "लॉगआउट",
        "profile": "प्रोफाइल",
        "home": "होम",
        "submit": "जमा करें",
        "cancel": "रद्द करें",
        "save": "सहेजें",
        "delete": "हटाएं",
        "edit": "संपादित करें",
        "your_smart_farming_assistant": "आपका एआई-संचालित स्मार्ट कृषि सहायक",
        "homepage_description": "बुद्धिमान फसल अनुशंसाओं, उर्वरक सुझावों, पौधों की बीमारी का पता लगाने और स्मार्ट खेत प्रबंधन उपकरणों के साथ भारतीय कृषि में क्रांति — सभी कई भारतीय भाषाओं में उपलब्ध हैं।",
        "explore_features": "विशेषताएं देखें",
        "get_started": "आरंभ करें",
        "get_crop_recommendations": "फसल अनुशंसाएँ प्राप्त करें",
        "username": "उपयोगकर्ता नाम",
        "password": "पासवर्ड",
        "email": "ईमेल",
        "forgot_password": "पासवर्ड भूल गए",
        "already_have_account": "क्या आपके पास पहले से एक खाता है?",
        "dont_have_account": "क्या आपके पास खाता नहीं है?",
        "sign_up": "साइन अप करें",
        "sign_in": "साइन इन करें",
        "nitrogen": "नाइट्रोजन",
        "phosphorus": "फास्फोरस",
        "potassium": "पोटैशियम",
        "temperature": "तापमान",
        "humidity": "आर्द्रता",
        "ph": "पीएच",
        "rainfall": "वर्षा",
        "crop_type": "फसल प्रकार",
        "soil_type": "मिट्टी प्रकार",
        "plant_image": "पौधे की छवि",
        "predict_crop": "फसल की भविष्यवाणी करें",
        "predict_fertilizer": "उर्वरक की भविष्यवाणी करें",
        "detect_disease": "रोग का पता लगाएं",
        "result": "परिणाम",
        "recommended_crop": "अनुशंसित फसल",
        "recommended_fertilizer": "अनुशंसित उर्वरक",
        "detected_disease": "पता लगाया गया रोग",
        "treatment": "उपचार",
        "prevention": "रोकथाम",
        "upload_image": "छवि अपलोड करें",
        "entry_type": "प्रविष्टि प्रकार",
        "date": "तारीख",
        "amount": "राशि",
        "details": "विवरण",
        "crop": "फसल",
        "add_entry": "प्रविष्टि जोड़ें",
        "export_diary": "डायरी निर्यात करें",
        "task_name": "कार्य नाम",
        "task_date": "कार्य तिथि",
        "task_type": "कार्य प्रकार",
        "task_details": "कार्य विवरण",
        "add_task": "कार्य जोड़ें",
        "completed": "पूरा हुआ",
        "pending": "लंबित",
        "mark_complete": "पूर्ण चिह्नित करें",
        "search": "खोज",
        "filter": "फ़िल्टर",
        "sowing": "बुवाई",
        "irrigation": "सिंचाई",
        "fertilizing": "उर्वरकीकरण",
        "harvesting": "कटाई",
        "income": "आय",
        "expense": "व्यय",
        "today": "आज",
        "tomorrow": "कल",
        "next_week": "अगले सप्ताह",
        "next_month": "अगले महीने",
        "voice_crop_planner": "वॉयस क्रॉप प्लानर",
        "voice_planner_description": "अपनी पसंदीदा भाषा में वैयक्तिकृत फसल सिफारिशें और योजना सलाह पाने के लिए अपनी आवाज़ का उपयोग करें।",
        "voice_assistant": "वॉयस सहायक",
        "help": "मदद",
        "stop": "रोकें",
        "voice_assistant_instructions": "अपनी मिट्टी के प्रकार, जलवायु या मौसम के आधार पर फसल की सिफारिशें पूछने के लिए प्राकृतिक रूप से बोलें।",
        "voice_shortcut_info": "दबाएँ",
        "to_activate_mic": "माइक्रोफोन सक्रिय करने के लिए",
        "suggested_queries": "सुझाए गए प्रश्न",
        "soil_based_queries": "मिट्टी आधारित प्रश्न",
        "what_to_plant_in_sandy_soil": "रेतीली मिट्टी में क्या लगाना चाहिए?",
        "crops_for_black_soil": "काली मिट्टी में कौन सी फसलें अच्छी उगती हैं?",
        "best_crops_for_clayey_soil": "चिकनी मिट्टी के लिए सबसे अच्छी फसलें?",
        "seasonal_queries": "मौसमी प्रश्न",
        "what_to_plant_in_rainy_season": "बारिश के मौसम में क्या लगाना चाहिए?",
        "winter_crop_recommendations": "सर्दियों के लिए फसलों की सिफारिश करें",
        "best_crops_for_summer": "गर्मी के मौसम के लिए सबसे अच्छी फसलें?",
        "how_it_works": "यह कैसे काम करता है",
        "speak": "बोलें",
        "speak_step_description": "अपनी मिट्टी, जलवायु या मौसम के आधार पर कौन सी फसलें लगानी हैं, इसके बारे में प्रश्न पूछें",
        "analyze": "विश्लेषण",
        "analyze_step_description": "सिस्टम उचित सिफारिशें उत्पन्न करने के लिए आपके प्रश्न का विश्लेषण करता है",
        "recommend": "अनुशंसा",
        "recommend_step_description": "बुवाई की सलाह के साथ व्यक्तिगत फसल सिफारिशें प्राप्त करें",
    },
    # Tamil phrases
    "ta": {
        "welcome": "அக்ரிசாரதிக்கு வரவேற்கிறோம்",
        "crop_recommendation": "பயிர் பரிந்துரை",
        "fertilizer_recommendation": "உர பரிந்துரை",
        "disease_detection": "நோய் கண்டறிதல்",
        "farm_diary": "பண்ணை நாட்குறிப்பு",
        "task_planner": "பணி திட்டமிடல்",
        "knowledge_hub": "அறிவு மையம்",
        "login": "உள்நுழைய",
        "register": "பதிவு செய்யவும்",
        "logout": "வெளியேறு",
        "profile": "சுயவிவரம்",
        "home": "முகப்பு",
        "submit": "சமர்ப்பிக்கவும்",
        "cancel": "ரத்து செய்",
        "save": "சேமி",
        "delete": "நீக்கு",
        "edit": "திருத்து",
        "voice_crop_planner": "குரல் பயிர் திட்டமிடல்",
        "voice_planner_description": "உங்கள் விருப்பமான மொழியில் தனிப்பயனாக்கப்பட்ட பயிர் பரிந்துரைகள் மற்றும் திட்டமிடல் ஆலோசனைகளைப் பெற உங்கள் குரலைப் பயன்படுத்தவும்.",
        "voice_assistant": "குரல் உதவியாளர்",
        "help": "உதவி",
        "stop": "நிறுத்து",
        "voice_assistant_instructions": "உங்கள் மண் வகை, காலநிலை அல்லது பருவத்தின் அடிப்படையில் பயிர் பரிந்துரைகளைக் கேட்க இயல்பாகப் பேசுங்கள்.",
        "voice_shortcut_info": "அழுத்தவும்",
        "to_activate_mic": "மைக்ரோஃபோனை செயல்படுத்த",
        "suggested_queries": "பரிந்துரைக்கப்பட்ட கேள்விகள்",
        "soil_based_queries": "மண் அடிப்படையிலான கேள்விகள்",
        "what_to_plant_in_sandy_soil": "மணல் மண்ணில் என்ன நடவு செய்ய வேண்டும்?",
        "crops_for_black_soil": "கரிசல் மண்ணில் எந்த பயிர்கள் நன்றாக வளரும்?",
        "best_crops_for_clayey_soil": "களிமண் மண்ணுக்கு சிறந்த பயிர்கள்?",
        "seasonal_queries": "பருவகால கேள்விகள்",
        "what_to_plant_in_rainy_season": "மழைக்காலத்தில் என்ன நடவு செய்ய வேண்டும்?",
        "winter_crop_recommendations": "குளிர்காலத்திற்கான பயிர்களை பரிந்துரைக்கவும்",
        "best_crops_for_summer": "கோடை காலத்திற்கு சிறந்த பயிர்கள்?",
        "how_it_works": "இது எப்படி செயல்படுகிறது",
        "speak": "பேசு",
        "speak_step_description": "உங்கள் மண், காலநிலை அல்லது பருவத்தை அடிப்படையாகக் கொண்டு எந்த பயிர்களை நடவு செய்வது என்பது குறித்து கேள்விகளைக் கேளுங்கள்",
        "analyze": "பகுப்பாய்வு",
        "analyze_step_description": "சிஸ்டம் பொருத்தமான பரிந்துரைகளை உருவாக்க உங்கள் கேள்வியை பகுப்பாய்வு செய்கிறது",
        "recommend": "பரிந்துரை",
        "recommend_step_description": "நடவு ஆலோசனையுடன் தனிப்பயனாக்கப்பட்ட பயிர் பரிந்துரைகளைப் பெறுங்கள்",
    },
    # Telugu phrases
    "te": {
        "welcome": "అగ్రిసారథికి స్వాగతం",
        "crop_recommendation": "పంట సిఫార్సు",
        "fertilizer_recommendation": "ఎరువుల సిఫార్సు",
        "disease_detection": "వ్యాధి గుర్తింపు",
        "farm_diary": "వ్యవసాయ డైరీ",
        "task_planner": "పని ప్రణాళిక",
        "knowledge_hub": "జ్ఞాన కేంద్రం",
        "login": "లాగిన్",
        "register": "నమోదు",
        "logout": "లాగౌట్",
        "profile": "ప్రొఫైల్",
        "home": "హోమ్",
        "submit": "సమర్పించండి",
        "cancel": "రద్దు చేయండి",
        "save": "సేవ్ చేయండి",
        "delete": "తొలగించండి",
        "edit": "సవరించండి",
        "voice_crop_planner": "వాయిస్ క్రాప్ ప్లానర్",
        "voice_planner_description": "మీ ఇష్టమైన భాషలో వ్యక్తిగతీకరించిన పంట సిఫార్సులు మరియు ప్రణాళిక సలహాలను పొందడానికి మీ స్వరాన్ని ఉపయోగించండి.",
        "voice_assistant": "వాయిస్ అసిస్టెంట్",
        "help": "సహాయం",
        "stop": "ఆపు",
        "voice_assistant_instructions": "మీ నేల రకం, వాతావరణం లేదా సీజన్ ఆధారంగా పంట సిఫార్సుల కోసం సహజంగా మాట్లాడండి.",
        "voice_shortcut_info": "నొక్కండి",
        "to_activate_mic": "మైక్రోఫోన్‌ను యాక్టివేట్ చేయడానికి",
        "suggested_queries": "సూచించిన ప్రశ్నలు",
        "soil_based_queries": "నేల ఆధారిత ప్రశ్నలు",
        "what_to_plant_in_sandy_soil": "ఇసుక నేలలో ఏమి నాటాలి?",
        "crops_for_black_soil": "నల్ల నేలలో ఏ పంటలు బాగా పెరుగుతాయి?",
        "best_crops_for_clayey_soil": "బంక మట్టి నేలకు ఉత్తమ పంటలు?",
        "seasonal_queries": "సీజనల్ ప్రశ్నలు",
        "what_to_plant_in_rainy_season": "వర్షాకాలంలో ఏమి నాటాలి?",
        "winter_crop_recommendations": "శీతాకాలానికి పంటలను సిఫార్సు చేయండి",
        "best_crops_for_summer": "వేసవి కాలానికి ఉత్తమ పంటలు?",
        "how_it_works": "ఇది ఎలా పని చేస్తుంది",
        "speak": "మాట్లాడండి",
        "speak_step_description": "మీ నేల, వాతావరణం లేదా సీజన్ ఆధారంగా ఏ పంటలు నాటాలి అనే దాని గురించి ప్రశ్నలు అడగండి",
        "analyze": "విశ్లేషించు",
        "analyze_step_description": "సిస్టమ్ సరైన సిఫార్సులను ఉత్పత్తి చేయడానికి మీ ప్రశ్నను విశ్లేషిస్తుంది",
        "recommend": "సిఫార్సు",
        "recommend_step_description": "నాటడం గురించి సలహాతో వ్యక్తిగతీకరించిన పంట సిఫార్సులను పొందండి",
    },
    # Bengali phrases
    "bn": {
        "welcome": "অগ্রিসারথিতে আপনাকে স্বাগতম",
        "crop_recommendation": "ফসল সুপারিশ",
        "fertilizer_recommendation": "সার সুপারিশ",
        "disease_detection": "রোগ সনাক্তকরণ",
        "farm_diary": "খামার ডায়েরি",
        "task_planner": "কাজ পরিকল্পনাকারী",
        "knowledge_hub": "জ্ঞান কেন্দ্র",
        "login": "লগইন",
        "register": "নিবন্ধন",
        "logout": "লগআউট",
        "profile": "প্রোফাইল",
        "home": "হোম",
        "submit": "জমা দিন",
        "cancel": "বাতিল করুন",
        "save": "সংরক্ষণ করুন",
        "delete": "মুছুন",
        "edit": "সম্পাদনা করুন",
        "voice_crop_planner": "ভয়েস ক্রপ প্ল্যানার",
        "voice_planner_description": "আপনার পছন্দের ভাষায় ব্যক্তিগতকৃত ফসল সুপারিশ এবং পরিকল্পনা পরামর্শ পেতে আপনার কণ্ঠস্বর ব্যবহার করুন।",
        "voice_assistant": "ভয়েস সহকারী",
        "help": "সাহায্য",
        "stop": "থামুন",
        "voice_assistant_instructions": "আপনার মাটির ধরন, জলবায়ু বা মৌসুমের উপর ভিত্তি করে ফসলের সুপারিশের জন্য স্বাভাবিকভাবে কথা বলুন।",
        "voice_shortcut_info": "চাপুন",
        "to_activate_mic": "মাইক্রোফোন সক্রিয় করতে",
        "suggested_queries": "প্রস্তাবিত প্রশ্ন",
        "soil_based_queries": "মাটি-ভিত্তিক প্রশ্ন",
        "what_to_plant_in_sandy_soil": "বালি মাটিতে কী রোপণ করা উচিত?",
        "crops_for_black_soil": "কালো মাটিতে কোন ফসল ভালো জন্মে?",
        "best_crops_for_clayey_soil": "কাদামাটির জন্য সেরা ফসল?",
        "seasonal_queries": "মৌসুমী প্রশ্ন",
        "what_to_plant_in_rainy_season": "বর্ষা মৌসুমে কী রোপণ করা উচিত?",
        "winter_crop_recommendations": "শীতকালের জন্য ফসল সুপারিশ করুন",
        "best_crops_for_summer": "গ্রীষ্মকালের জন্য সেরা ফসল?",
        "how_it_works": "এটি কীভাবে কাজ করে",
        "speak": "বলুন",
        "speak_step_description": "আপনার মাটি, জলবায়ু বা মৌসুমের উপর ভিত্তি করে কোন ফসল রোপণ করতে হবে সে সম্পর্কে প্রশ্ন জিজ্ঞাসা করুন",
        "analyze": "বিশ্লেষণ",
        "analyze_step_description": "সিস্টেম উপযুক্ত সুপারিশ তৈরি করতে আপনার প্রশ্ন বিশ্লেষণ করে",
        "recommend": "সুপারিশ",
        "recommend_step_description": "রোপণের পরামর্শ সহ ব্যক্তিগতকৃত ফসল সুপারিশ পান",
    },
}

def translate_text(text, target_language='en'):
    """
    Translate text using predefined translations.
    
    Args:
        text (str): Text to translate
        target_language (str): Target language code (e.g., 'hi' for Hindi, 'ta' for Tamil)
        
    Returns:
        str: Translated text
    """
    if not text:
        return ""
    
    # Default to English if target language not supported
    if target_language not in TRANSLATIONS:
        target_language = 'en'
    
    # Look up the text in our translations dictionary
    for key, translated_text in TRANSLATIONS[target_language].items():
        if text.lower() == key.lower():
            return translated_text
        
    # If we don't have a translation, return the original text
    return text

# Dictionary of supported languages with their codes
SUPPORTED_LANGUAGES = {
    "English": "en",
    "Hindi": "hi",
    "Tamil": "ta",
    "Telugu": "te",
    "Bengali": "bn",
    "Marathi": "mr",
    "Gujarati": "gu",
    "Kannada": "kn",
    "Malayalam": "ml",
    "Punjabi": "pa",
    "Urdu": "ur"
}
